Repository SMJ426/KPaaS, pull requests merged in 2024-10, with the labels that each got.

#37 Fix/mobile-blocker: 모바일 접속 차단의 오타를 수정합니다.
  src/components/UI/MobileCheckModal.jsx
Labels: fix

#38 Refactor/chatting-version-two: 채팅 관련 버그 수정과 리팩토링을 진행합니다.
  public/svgs/chat_of_no_partner.svg
  src/components/chat/chatConversationPanel/ChatClassOverview.jsx
  src/components/chat/chatConversationPanel/ChatConversationPanel.jsx
  src/components/chat/chatConversationPanel/ChatPartnerProfile.jsx
  src/components/chat/chatConversationPanel/NoChattingPartner.jsx
  src/components/chat/chatConversationPanel/ReceivedMessages.jsx
  src/components/chat/chatConversationPanel/RequestMessages.jsx
  src/components/chat/chatListPanel/ChatListPanel.jsx
  src/components/chat/chatListPanel/ChattingListRenderer.jsx
  src/components/chat/chatListPanel/NoChattingRooms.jsx
  src/components/chat/chatListPanel/testData/ChattingListTestData.js
Labels: fix, refactor

#41 fix: post update 부, 오탈자 등의 오류(4개)를 수정했습니다.
  src/components/posts/Interaction/Edit-page.jsx
  src/components/posts/Interaction/SendPost.jsx
  src/components/posts/Interaction/SendPostbtn.jsx
Labels: fix

#45 hotfix#1 : sns 로그인 redirecturl(카카오 전송 목적) 강사,회원 통일
  src/components/login/TeacherSocialLogin.jsx
Labels: hotfix

#47 Hotfix/login-ui: 로그인 부분을 핫픽스합니다.
  src/components/login/ChoiceComponents.jsx
Labels: hotfix

#42 결제 부 오류 사항 (2개) 수정 했습니다
  src/components/payment/ChoosePay.jsx
  src/components/payment/PTPaymentsEndComponents.jsx
  src/components/payment/payment.jsx
Labels: fix

#46 fix#1 : 프로필 조그만 이미지 반복 클릭 시 , 오류 발생 문제 해결
  src/components/profile/SmallProfile.jsx
Labels: fix

#49 fix#1 : 길 찾기 카카오맵 아이콘 + 노란색 UI로 통일
  public/images/png/kakaomap_basic.png
  src/components/main/announcementMap/KakaoMap.jsx
Labels: fix

#53 style(main-page): 메인 페이지 주된 스타일들을 변경합니다.
  src/components/main/announcementPolicy/AnnouncementPolicy.jsx
  src/components/main/announcementPolicy/PolicyRenderer.jsx
  src/components/posts/PostsGrid.jsx
  src/containers/MainContainers.jsx
Labels: fix

#52 fix#1 : sns 로그인 시 동일 인 중복 naver or kakao 아이디 회원가입 예외처리
  src/app/user/login/oauth2/kakao/page.jsx
  src/app/user/login/oauth2/naver/page.jsx
  src/app/user/teacherlogin/oauth2/kakao/page.jsx
  src/app/user/teacherlogin/oauth2/naver/page.jsx
Labels: hotfix

#50 fix#1: 의존성 추가, 'framer-motion'
  package-lock.json
  package.json
Labels: fix

#55 Fix/notice metion
  src/components/main/announcementPolicy/AnnouncementPolicy.jsx
  src/components/main/announcementPolicy/PolicyRenderer.jsx
  src/containers/MainContainers.jsx
  src/containers/SearchContainer.jsx
Labels: fix

#59 fix#1 : 피드백 반영 (이미지 변경, pt 목록 틈 띄우기, 복지 ui 색상 통일, 결제 후 안내 문구 변경)
  public/images/policy/pt체험유튜브.jpg
  public/images/policy/복권위원회.jpg
  public/images/policy/스포츠강좌이용권 신청유튜브.jpg
  public/images/policy/스포츠이용권사이트.jpg
  public/images/policy/장애인체육회.jpg
  src/components/main/announcementPolicy/AnnouncementPolicy.jsx
  src/components/main/announcementPolicy/PolicyRenderer.jsx
  src/components/payment/ChoosePay.jsx
  src/components/posts/Interaction/Edit-page.jsx
  src/components/posts/Interaction/SendPost.jsx
  src/components/profile/EditProfile.jsx
  src/components/signup/SignupForm.jsx
  src/components/signup/Teacher-SignupForm.jsx
  src/constants/AnnouncementTestDataSet.js
  src/containers/MainContainers.jsx
  src/containers/SearchContainer.jsx
Labels: fix

#66 Refactor/image-resize: 프로필 이미지가 늘어나는 현상 수정
  src/components/profile/ProfileOptions/MainProfile.jsx
  src/components/profile/ProfileOptions/OtherMainProfile.jsx
Labels: refactor
